language: node_js
arch:
 - amd64
 - ppc64le
node_js:
  - 'stable'
  - '9'
  - '8'
  - '7'
  - '6'
  - '6.0.0'
  - '5'
  - '5.0.0'
  - '4'
  - '4.4.0'
  - '4.0.0'
  - '0.12'
  - '0.12.0'
  - '0.10'
  - '0.8'
  - '0.8.6'
matrix:
  include:
    - node_js: 'stable'
      script: npm install browserify && npm run browserify-test
 # exlcude unsupport power jobs node 0.10,0.12

matrix:
  exclude:
  -arch: ppc64le
      - node_js: '0.12'  
  -arch: ppc64le
      - node_js: '0.12.0'
  -arch: ppc64le
      - node_js: '0.8'
  -arch: ppc64le
      - node_js: '0.8.6'
before_install:
  - 'case "${TRAVIS_NODE_VERSION}" in 0.*) export NPM_CONFIG_STRICT_SSL=false ;; esac'
  - 'nvm install-latest-npm'
notifications:
  email: false
